# lightweight image
FROM golang:1.21-alpine3.18

# or full golang
#FROM golang:1.21

# installs the base
RUN apk add build-base
RUN apk upgrade --no-cache

#sets work directory
WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and 
# only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

#copies contents of app directory
COPY . .

# sets a listening port
EXPOSE 9000

#sets ennvironment and makes sure CGO is there for sqlite3
RUN GOOS=linux CGO_ENABLED=1 GOARCH=amd64 go build -v -o /usr/local/bin/app .

#runs the app
CMD [ "app" ]
